#!/usr/bin/env python3
import myokit
import matplotlib.pyplot as plt

p = myokit.load_protocol('simplified-staircase.mmt')

a = 0
b = p.characteristic_time()
if b == 0:
    b = 1000
d = p.create_log_for_interval(a, b, for_drawing=True)
plt.figure()
plt.plot(d['time'], d['pace'])
lo, hi = p.range()
if lo == 0 and hi == 1:
    plt.ylim(-0.1, 1.1)
else:
    r = (hi - lo) * 0.1
    plt.ylim(lo - r, hi + r)
plt.show()
